### ISSUE TITLE
Add support for Custom Scalars

### ISSUE THREAD

**Issue by acron0** [WorksHub/leona#7]
We would like to be able to define and use [custom scalars](https://lacinia.readthedocs.io/en/latest/custom-scalars.html) so that we can define things like `::date` appropriately. They should be linked to a spec and exercised whenever that spec is used. They should use the `attach-` syntax.

**Comment by Heliosmaster** [comment]
lacinia version 0.31 (so newer than the version this lib is using) [made some breaking changes](https://github.com/walmartlabs/lacinia/blob/master/CHANGES.md) in how custom scalars are implemented. It's probably good to keep it in mind before addressing this issue.

**Comment by acron0** [comment]
> lacinia version 0.31 (so newer than the version this lib is using) [made some breaking changes](https://github.com/walmartlabs/lacinia/blob/master/CHANGES.md) in how custom scalars are implemented. It's probably good to keep it in mind before addressing this issue.

Leona now uses 0.31 👍
